#name: Rust CD
## Run when Rust CI run completed
#on:
#  workflow_run:
#    workflows: ["Rust CI"]
#    types:
#      - completed
#
#jobs:
#  setup-database:
#    name: Setup Postgres Container
#    runs-on: self-hosted
#    steps:
#      - name: Pull Postgres Image
#        run: docker pull postgres:16-alpine
#      - name: Delete old container
#        run: docker rm -f postgres-container || true
#      - name: Run Postgres Container
#        run: docker run --name postgres-container -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} -p 5432:5432 postgres:16-alpine
#  deploy-docker:
#    name: Deploy Docker Container
#    runs-on: self-hosted
#    steps:
#      - name: Pull Docker Image
#        run: docker pull andrewtran2801/rust-api-services:latest
#      - name: Delete old container
#        run: docker rm -f rust-api-container || true
#      - name: Run Docker Container
#        run: docker run --name rust-api-container --link=postgres-container -p 3030:3030 andrewtran2801/rust-api-services:latest
